const mongoose = require('mongoose');

const appSchema = new mongoose.Schema({
  id: { type: String, required: true, unique: true },
  type: { type: String, enum: ['game', 'app'], required: true },
  name: { type: String, required: true, maxlength: 60 },
  shortDescription: { type: String, required: true, maxlength: 100 },
  longDescription: { type: String },
  category: { type: String, required: true },
  additionalCategories: { type: [String], default: [] },
  categories: { type: [String], default: [] },
  icon: { type: String, required: true },
  bannerImages: { type: [String], default: [] },
  banner: { type: String },
  clicks: { type: Number, default: 0 },
  telegramStarsDonations: { type: Number, default: 0 },
  votes: { type: Number, default: 0 },
  userRating: { type: Number, default: 0 },
  dateAdded: { type: String, required: true },
  complaints: { type: Number, default: 0 },
  adminId: { type: String, required: true },
  adminEmail: { type: String, required: true },
  isTopInCatalog: { type: Boolean, default: false },
  isTopInCategory: { type: Boolean, default: false },
  isPromotedInCatalog: { type: Boolean, default: false },
  isPromotedInCategory: { type: Boolean, default: false },
  isVip: { type: Boolean, default: false },
  status: { type: String, enum: ['added', 'onModeration', 'rejected'], default: 'onModeration' },
  rejectionReason: { type: String },
  developerId: { type: String, required: true },
  platforms: { type: [String], default: [] },
  ageRating: { type: String },
  inAppPurchases: { type: Boolean, default: false },
  supportsTON: { type: Boolean, default: false },
  supportsTelegramStars: { type: Boolean, default: false },
  contactInfo: { type: String },
  gallery: { type: [String], default: [] },
  video: { type: String },
  promotion: {
    catalog: { active: { type: Boolean, default: false }, endDate: { type: String } },
    category: { active: { type: Boolean, default: false }, endDate: { type: String } },
  },
});

module.exports = mongoose.model('App', appSchema);